sudo: required
dist: trusty

language: go
go:
        - 1.8.1
go_import_path: github.com/GoogleCloudPlatform/container-diff

script:
 - ./.gofmt.sh
 - sudo rm -rf /etc/docker
 - travis_wait ./container-diff-tests.sh
